version: '3.5'
services:
  asr-api:
    container_name: asr-api
    image: asr-api:0.0.1
    build:
      context: .
      dockerfile: ./docker/asr-api.Dockerfile
    volumes:
      - ./data:/app/data
      - ./conf:/app/conf
    ports:
      - "8001:8001"
    environment:
      - FLASK_APP=asr_api.py
    tty: true
