version: '3.5'

services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - http.cors.enabled=true
      - http.cors.allow-origin="*"
      - http.cors.allow-methods="OPTIONS, HEAD, GET, POST, PUT, DELETE"
      - http.cors.allow-headers="Accept, Access-Control-Allow-Headers, Authorization, Content-Type, Cache-Control, Origin, Pragma, X-Requested-With, x-elastic-client-meta"
      - http.cors.allow-credentials=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic

  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    container_name: es02
    depends_on:
      - es01
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - http.cors.enabled=true
      - http.cors.allow-origin="*"
      - http.cors.allow-methods="OPTIONS, HEAD, GET, POST, PUT, DELETE"
      - http.cors.allow-headers="Accept, Access-Control-Allow-Headers, Authorization, Content-Type, Cache-Control, Origin, Pragma, X-Requested-With, x-elastic-client-meta"
      - http.cors.allow-credentials=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data02:/usr/share/elasticsearch/data
    networks:
      - elastic

  search-ui:
    container_name: search-ui
    image: search-ui:0.0.1
    build:
      context: .
      dockerfile: docker/react-search.Dockerfile
    depends_on:
      - es01
      - es02
    # environment:
    #   - REACT_APP_ELASTICSEARCH_HOST=http://localhost:9200
    ports:
      - 3000:3000
    networks:
      - elastic

volumes:
  data01:
  data02:

networks:
  elastic:
    driver: bridge
